### PR TITLE
Create PrintMatrixDiagonal.java

### PR DESCRIPTION
**Pull request by SayedZahur786**
Created a Program to Print all the Diagonal Elements of a 2D Array

### CODE REVIEW

**Comment by MTalhaofc** [comment]
Don't forget to STAR the Repo and Follow me on Github.

**Comment by SayedZahur786** [comment]
> Don't forget to STAR the Repo and Follow me on Github.

Done Sir Please Merge my Pull Request, Thanks

**Comment by MTalhaofc** [comment]
MERGED!!

**Comment by SayedZahur786** [comment]
> MERGED!!

Thanks a Lot

**Comment by SayedZahur786** [comment]
> MERGED!!

Sir Can I add one more program and raise another request

**Comment by SayedZahur786** [comment]
> Go Ahead.

Initiated a PR, Please Review and Merge 
Thanks

**Pull request merged**
